stages:
    - build_and_test
    - push_to_dockerhub
    - deploy

build_job:
    stage: build_and_test
    script:
        - docker build -t notes-app:latest
    tags:
        - dev
    artifacts:
        paths:
            - builds/
        expire_in: 1 day

    push_job:
    stage: push_to_dockerhub
    script:
        - docker login -u -p
        - docker image tag
        - docker push notes-app:latest
    tags:
        - dev
    artifacts:
        paths:
            - builds/
        expire_in: 1 day

deploy_job:
    stage: deploy
    script: 
        - docker compose up -d
